name: "Generate Release Package"

on:
    push:
        branches: ["main"]

permissions:
    packages: write
    contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        python -m pip install poetry;
        cd app;
        version=$(python -m poetry version -s);
        gh release create "v$version" -t "JobRec v$version" --generate-notes;